### ISSUE TITLE
bbb, detect.go, func nodeName(): host name limited to beaglebone

### ISSUE THREAD

**Issue by gritty** [kidoman/embd#16]
I have a number of Beaglebone Black computers, not a single one is still named "beaglebone".  Is there some other way besides "uname -n" that the actuall computer can be verified as a beaglebone computer?  I really don't want to hack the code on my computer just so I can run "embd".

**Comment by benjamind** [comment]
Perhaps using /proc/cpuinfo might be more appropriate?

On a BBB you would have a model name containing ARMv7, and a Hardware line containing AM33XX. On a Raspberry Pi you would have Hardware line containing BCM2708 and you could use the Revision line to determine pi version.

**Comment by kidoman** [comment]
It should be good now. Thanks to @benjamind for contributing the fix.
