### ISSUE TITLE
LCD Driver

### ISSUE THREAD

**Issue by aleksclark** [kidoman/embd#29]
Sup! I just put up an LCD driver that leverages embd, was wondering if you thought it should be merged into the main codebase. Since I wanted to be able to update the LCDs from different goroutines, I also implemented a shared i2c writer and port abstraction:

https://github.com/aleksclark/portwriter
https://github.com/aleksclark/embd-lcd
https://github.com/aleksclark/sharedi2c

**Comment by kidoman** [comment]
Why did you close it?

**Comment by aleksclark** [comment]
Hey Karan,

I only just noticed that there was already an i2c/lcd interface already
included in embd, while browsing the embd forks. It seems to work in a
straightforward manner :) Right now the only feature that's really not
there is the channel-based i2c writer, I need to think about how to go
about implementing that with the existing code, or if it's even worth doing
so.

On Sat, May 23, 2015 at 11:27 PM, Karan Misra <notifications@github.com>
wrote:

> Why did you close it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kidoman/embd/issues/29#issuecomment-104978191>.
>



-- 
Aleks Clark
cell: 775-391-6114
