### ISSUE TITLE
panic: Error embd: your host ": ARMv6-compatible processor rev 7 (v6l)" is not supported at this moment.

### ISSUE THREAD

**Issue by jdevelop** [kidoman/embd#83]
Any chance to get this supported?

Thanks!

**Comment by dougthebug** [comment]
I'm working with CHIP and I'm getting a similar error:

2017/04/19 17:12:19 GPIO main: embd.InitGPIO: embd: your host ": ARMv7 Processor rev 2 (v7l)" is not supported at this moment. request support at https://github.com/kidoman/embd/issues

Any ideas?

**Comment by lukepalmer** [comment]
You need a change to detect.go that looks something like #79, then of course to test with your hardware. Please send a PR!

**Comment by dougthebug** [comment]
Thank you!

I'll take a look when I get home.

-Doug
